# Default values for podinfo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/stefanprodan/podinfo
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "6.7.1"
  # Overrides the default command
  command:
    - ./podinfo
    - --port=9898
    - --port-metrics=9797
    - --grpc-port=9999
    - --grpc-service-name=podinfo
    - --level=info
    - --random-delay=false
    - --random-error=false
  # Adds the environment variables
  env:
    - name: PODINFO_UI_COLOR
      value: "#34577c"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  ports:
    - name: http
      port: 9898
    - name: http-metrics
      port: 9797
    - name: grpc
      port: 9999

ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: podinfo.example
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 2000m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 64Mi

livenessProbe:
  exec:
    command:
    - podcli
    - check
    - http
    - localhost:9898/healthz
  initialDelaySeconds: 5
  timeoutSeconds: 5
readinessProbe:
  exec:
    command:
    - podcli
    - check
    - http
    - localhost:9898/readyz
  initialDelaySeconds: 5
  timeoutSeconds: 5

# Additional volumes on the output Deployment definition.
volumes:
- name: data
  emptyDir: {}

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
- name: data
  mountPath: "/data"

nodeSelector: {}

tolerations: []

affinity: {}
